# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)
  lane :beta do
      ensure_git_status_clean
      increment_build_number
      commit_version_bump
      add_git_tag
      build_app(
          workspace: "YOUR.xcworkspace",
          scheme: "YOURMAIN",
          clean: true
          )
      upload_to_testflight(
          app_identifier: "YOUR_BUNDLE_ID"
          )
  end

  lane :screenshots do
    capture_screenshots(workspace: "YOUR.xcworkspace", scheme: "YOUR_UITEST_SCHEME")
    frame_screenshots(white: true)
  end
end
